// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3QLO-Sj_dmalrePGUEbYwEG4ily8mhnk',
    appId: '1:23451253578:web:81f6caa00e3490a49b5fb3',
    messagingSenderId: '23451253578',
    projectId: 'authentificationdjangofirebase',
    authDomain: 'authentificationdjangofirebase.firebaseapp.com',
    storageBucket: 'authentificationdjangofirebase.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOfFdmH29GsgyXf80GOLOlVy88AAfWKL4',
    appId: '1:23451253578:android:de9daae461e5fa759b5fb3',
    messagingSenderId: '23451253578',
    projectId: 'authentificationdjangofirebase',
    storageBucket: 'authentificationdjangofirebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8EyVGr_mdNJvjJZM_1gnGdlhViN1u7ZI',
    appId: '1:23451253578:ios:2540eb00fb5e5e319b5fb3',
    messagingSenderId: '23451253578',
    projectId: 'authentificationdjangofirebase',
    storageBucket: 'authentificationdjangofirebase.appspot.com',
    iosClientId: '23451253578-o2j9421a12rkvovv5choq5cli6gve7tj.apps.googleusercontent.com',
    iosBundleId: 'com.example.authentificationDjangoFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8EyVGr_mdNJvjJZM_1gnGdlhViN1u7ZI',
    appId: '1:23451253578:ios:2540eb00fb5e5e319b5fb3',
    messagingSenderId: '23451253578',
    projectId: 'authentificationdjangofirebase',
    storageBucket: 'authentificationdjangofirebase.appspot.com',
    iosClientId: '23451253578-o2j9421a12rkvovv5choq5cli6gve7tj.apps.googleusercontent.com',
    iosBundleId: 'com.example.authentificationDjangoFirebase',
  );
}
